name: upsi_tester
description: "upsi - a decentraliced STI tracing approach"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter
  upsi_core:
    path: ../upsi-core
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.5
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_local_notifications: ^17.1.2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  linux: false
  image_path: "resources/images/upsi_icon_yellow.png"

flutter:
  # for l10n
  generate: true
  uses-material-design: true
  assets:
    - .env
    - resources/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: resources/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: resources/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: resources/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: resources/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: resources/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: resources/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: resources/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: resources/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: resources/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
    - family: SFProText
      fonts:
        - asset: resources/fonts/SF-Pro-Text-Black.otf
          weight: 900
        - asset: resources/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: resources/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: resources/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: resources/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: resources/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: resources/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: resources/fonts/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: resources/fonts/SF-Pro-Text-Ultralight.otf
          weight: 100
