name: Android Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        cache: true
    - run: flutter pub get
#      todo: activate test
#    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}