# https://github.com/nabilnalakath/flutter-githubaction
# https://blog.logrocket.com/flutter-ci-cd-using-github-actions/

name: Android Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v4
        with:
          name: gitversion
          path: version.txt

  build:
    name: Build
    needs: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get version.txt
      uses: actions/download-artifact@v4
      with:
        name: gitversion

    - name: Create new file without newline char from version.txt
      run: tr -d '\n' < version.txt > version1.txt

    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version1.txt

    - name: Update version in YAML
      run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '12.x'
        cache: 'gradle'

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Build app
      run: flutter build appbundle

    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/bundle/release/app-release.aab"
        token: ${{ secrets.TOKEN }}

#  tag:
#    name: Tag
#    needs: version
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - uses: rickstaa/action-create-tag@v1
#        id: tag
#        with:
#          tag: ${{ steps.version.outputs.content }}
#          tag_exists_error: false
#
#  release:
#    name: Release
#    needs: [tag, build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: build/app/outputs/bundle/release/app-release.aab
#          name: ${{ steps.version.outputs.content }}

#    - name: Upload Android Release
#      uses: actions/upload-artifact@v4
#      with:
#        name: android-release
#        path: build/app/outputs/bundle/release/app-release.aab