# https://github.com/nabilnalakath/flutter-githubaction
# https://blog.logrocket.com/flutter-ci-cd-using-github-actions/

name: Android Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  version:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: create version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1

#      - name: Create version.txt with nuGetVersion
#        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

#      - name: Upload version.txt
#        uses: actions/upload-artifact@v4
#        with:
#          name: gitversion
#          path: version.txt

#  tag:
#    name: Tag
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - uses: rickstaa/action-create-tag@v1
#        id: tag
#        with:
#          tag: "latest"
#          tag: ${{ steps.version.outputs.content }}
#          tag_exists_error: false

#  build:
#    name: Build
#    needs: [version, tag]
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4

#    - name: Get version.txt
#      uses: actions/download-artifact@v4
#      with:
#        name: gitversion
#
#    - name: Create new file without newline char from version.txt
#      run: tr -d '\n' < version.txt > version1.txt
#
#    - name: Read version
#      id: version
#      uses: juliangruber/read-file-action@v1
#      with:
#        path: version1.txt

      - name: update version in pubspec
#      run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
        run: sed -i 's/99.99.99+99/${{ steps.gitversion.outputs.nuGetVersion }}+${{ github.run_number }}/g' pubspec.yaml

      - name: create tag
        uses: rickstaa/action-create-tag@v1
        id: tag
        with:
  #        tag: "latest"
          tag: ${{ steps.gitversion.outputs.nuGetVersion }}
          tag_exists_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true

      - name: get dependencies
        run: flutter pub get

      - name: build app
        run: flutter build appbundle

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GITHUB_TOKEN }}

#
#  release:
#    name: Release
#    needs: [tag, build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: build/app/outputs/bundle/release/app-release.aab
#          name: ${{ steps.version.outputs.content }}

#    - name: Upload Android Release
#      uses: actions/upload-artifact@v4
#      with:
#        name: android-release
#        path: build/app/outputs/bundle/release/app-release.aab