# https://github.com/nabilnalakath/flutter-githubaction
# https://blog.logrocket.com/flutter-ci-cd-using-github-actions/

name: Android Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: create version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: update version in pubspec
        run: sed -i 's/99.99.99+99/${{ steps.gitversion.outputs.nuGetVersion }}+${{ github.run_number }}/g' pubspec.yaml

      - name: create tag
        uses: rickstaa/action-create-tag@v1
        id: tag
        with:
          tag: ${{ steps.gitversion.outputs.nuGetVersion }}
          tag_exists_error: false

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true

      - name: get dependencies
        run: flutter pub get

      - name: l10n
        run: flutter gen-l10n

      - name: code generation
        run: dart run build_runner build

      - name: test
        run: flutter test

      - name: build app
        run: flutter build appbundle

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.gitversion.outputs.nuGetVersion }}